# Generated by Django 3.2.16 on 2022-11-24 14:06

import cloudinary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0002_alter_recipe_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='calories',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='carbs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fat',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='protein',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.TextField(blank=True),
        ),
    ]
