# Generated by Django 3.2.16 on 2022-11-24 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20221124_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.TextField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
