# Generated by Django 3.2.16 on 2022-11-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20221124_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbs',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='directions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='protein',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
